// Custom LaTeX macros for MathJax
// These will be available throughout the entire website

export const mathjaxMacros = {
  // ===== MATH OPERATORS =====
  coker: '{\\operatorname{coker}}',
  Spec: '{\\operatorname{Spec}}',
  Proj: '{\\operatorname{Proj}}',
  Cl: '{\\operatorname{Cl}}',
  Div: '{\\operatorname{Div}}',
  ddiv: '{\\operatorname{div}}',
  Pic: '{\\operatorname{Pic}}',
  lcm: '{\\operatorname{lcm}}',
  rank: '{\\operatorname{rank}}',
  rk: '{\\operatorname{rk}}',
  Vol: '{\\operatorname{Vol}}',
  Supp: '{\\operatorname{Supp}}',
  codim: '{\\operatorname{codim}}',
  height: '{\\operatorname{ht}}',
  ord: '{\\operatorname{ord}}',
  image: '{\\operatorname{im}}',
  coimage: '{\\operatorname{coim}}',
  Hom: '{\\operatorname{Hom}}',
  mor: '{\\operatorname{mor}}',
  Mor: '{\\operatorname{Mor}}',
  Trace: '{\\operatorname{Tr}}',
  dif: '{\\mathop{}\\!\\mathrm{d}}',
  argmin: '{\\operatorname*{arg\\,min}}',

  // ===== BLACKBOARD BOLD LETTERS =====
  // Lowercase shortcuts
  ba: '{\\mathbb{A}}',
  bb: '{\\mathbb{B}}',
  bc: '{\\mathbb{C}}',
  bd: '{\\mathbb{D}}',
  be: '{\\mathbb{E}}',
  bbf: '{\\mathbb{F}}',
  bg: '{\\mathbb{G}}',
  bh: '{\\mathbb{H}}',
  bi: '{\\mathbb{I}}',
  bj: '{\\mathbb{J}}',
  bk: '{\\mathbb{K}}',
  bl: '{\\mathbb{L}}',
  bbm: '{\\mathbb{M}}',
  bn: '{\\mathbb{N}}',
  bo: '{\\mathbb{O}}',
  bp: '{\\mathbb{P}}',
  bq: '{\\mathbb{Q}}',
  br: '{\\mathbb{R}}',
  bs: '{\\mathbb{S}}',
  bt: '{\\mathbb{T}}',
  bu: '{\\mathbb{U}}',
  bv: '{\\mathbb{V}}',
  bw: '{\\mathbb{W}}',
  bx: '{\\mathbb{X}}',
  by: '{\\mathbb{Y}}',
  bz: '{\\mathbb{Z}}',

  // Uppercase shortcuts
  AA: '{\\mathbb{A}}',
  BB: '{\\mathbb{B}}',
  CC: '{\\mathbb{C}}',
  DD: '{\\mathbb{D}}',
  EE: '{\\mathbb{E}}',
  FF: '{\\mathbb{F}}',
  GG: '{\\mathbb{G}}',
  HH: '{\\mathbb{H}}',
  II: '{\\mathbb{I}}',
  JJ: '{\\mathbb{J}}',
  KK: '{\\mathbb{K}}',
  LL: '{\\mathbb{L}}',
  MM: '{\\mathbb{M}}',
  NN: '{\\mathbb{N}}',
  OO: '{\\mathbb{O}}',
  PP: '{\\mathbb{P}}',
  QQ: '{\\mathbb{Q}}',
  RR: '{\\mathbb{R}}',
  SS: '{\\mathbb{S}}',
  TT: '{\\mathbb{T}}',
  UU: '{\\mathbb{U}}',
  VV: '{\\mathbb{V}}',
  WW: '{\\mathbb{W}}',
  XX: '{\\mathbb{X}}',
  YY: '{\\mathbb{Y}}',
  ZZ: '{\\mathbb{Z}}',
  kk: '{\\Bbbk}',

  // ===== MATHSCR LETTERS =====
  sca: '{\\mathscr{A}}',
  scb: '{\\mathscr{B}}',
  scc: '{\\mathscr{C}}',
  scd: '{\\mathscr{D}}',
  sce: '{\\mathscr{E}}',
  scf: '{\\mathscr{F}}',
  scg: '{\\mathscr{G}}',
  sch: '{\\mathscr{H}}',
  sci: '{\\mathscr{I}}',
  scj: '{\\mathscr{J}}',
  sck: '{\\mathscr{K}}',
  scl: '{\\mathscr{L}}',
  scm: '{\\mathscr{M}}',
  scn: '{\\mathscr{N}}',
  sco: '{\\mathscr{O}}',
  scp: '{\\mathscr{P}}',
  scq: '{\\mathscr{Q}}',
  scs: '{\\mathscr{S}}',
  sct: '{\\mathscr{T}}',
  scu: '{\\mathscr{U}}',
  scv: '{\\mathscr{V}}',
  scw: '{\\mathscr{W}}',
  scx: '{\\mathscr{X}}',
  scy: '{\\mathscr{Y}}',
  scz: '{\\mathscr{Z}}',

  // ===== MATHFRAK LETTERS =====
  // Lowercase
  fa: '{\\mathfrak{a}}',
  fb: '{\\mathfrak{b}}',
  fc: '{\\mathfrak{c}}',
  fd: '{\\mathfrak{d}}',
  fe: '{\\mathfrak{e}}',
  ff: '{\\mathfrak{f}}',
  fg: '{\\mathfrak{g}}',
  fh: '{\\mathfrak{h}}',
  fii: '{\\mathfrak{i}}',
  fj: '{\\mathfrak{j}}',
  fk: '{\\mathfrak{k}}',
  fl: '{\\mathfrak{l}}',
  fm: '{\\mathfrak{m}}',
  fn: '{\\mathfrak{n}}',
  fo: '{\\mathfrak{o}}',
  fp: '{\\mathfrak{p}}',
  fq: '{\\mathfrak{q}}',
  fr: '{\\mathfrak{r}}',
  fs: '{\\mathfrak{s}}',
  ft: '{\\mathfrak{t}}',
  fu: '{\\mathfrak{u}}',
  fv: '{\\mathfrak{v}}',
  fw: '{\\mathfrak{w}}',
  fx: '{\\mathfrak{x}}',
  fy: '{\\mathfrak{y}}',
  fz: '{\\mathfrak{z}}',

  // Uppercase
  fA: '{\\mathfrak{A}}',
  fB: '{\\mathfrak{B}}',
  fC: '{\\mathfrak{C}}',
  fD: '{\\mathfrak{D}}',
  fE: '{\\mathfrak{E}}',
  fF: '{\\mathfrak{F}}',
  fG: '{\\mathfrak{G}}',
  fH: '{\\mathfrak{H}}',
  fI: '{\\mathfrak{I}}',
  fJ: '{\\mathfrak{J}}',
  fK: '{\\mathfrak{K}}',
  fL: '{\\mathfrak{L}}',
  fM: '{\\mathfrak{M}}',
  fN: '{\\mathfrak{N}}',
  fO: '{\\mathfrak{O}}',
  fP: '{\\mathfrak{P}}',
  fQ: '{\\mathfrak{Q}}',
  fR: '{\\mathfrak{R}}',
  fS: '{\\mathfrak{S}}',
  fT: '{\\mathfrak{T}}',
  fU: '{\\mathfrak{U}}',
  fV: '{\\mathfrak{V}}',
  fW: '{\\mathfrak{W}}',
  fX: '{\\mathfrak{X}}',
  fY: '{\\mathfrak{Y}}',
  fZ: '{\\mathfrak{Z}}',

  // ===== MATHCAL LETTERS =====
  cA: '{\\mathcal{A}}',
  cB: '{\\mathcal{B}}',
  cC: '{\\mathcal{C}}',
  cD: '{\\mathcal{D}}',
  cE: '{\\mathcal{E}}',
  cF: '{\\mathcal{F}}',
  cG: '{\\mathcal{G}}',
  cH: '{\\mathcal{H}}',
  cI: '{\\mathcal{I}}',
  cJ: '{\\mathcal{J}}',
  cK: '{\\mathcal{K}}',
  cL: '{\\mathcal{L}}',
  cM: '{\\mathcal{M}}',
  cN: '{\\mathcal{N}}',
  cO: '{\\mathcal{O}}',
  cP: '{\\mathcal{P}}',
  cQ: '{\\mathcal{Q}}',
  cR: '{\\mathcal{R}}',
  cS: '{\\mathcal{S}}',
  cT: '{\\mathcal{T}}',
  cU: '{\\mathcal{U}}',
  cV: '{\\mathcal{V}}',
  cW: '{\\mathcal{W}}',
  cX: '{\\mathcal{X}}',
  cY: '{\\mathcal{Y}}',
  cZ: '{\\mathcal{Z}}',

  // ===== MATHSF LETTERS =====
  sA: '{\\mathsf{A}}',
  sB: '{\\mathsf{B}}',
  sC: '{\\mathsf{C}}',
  sD: '{\\mathsf{D}}',
  sE: '{\\mathsf{E}}',
  sF: '{\\mathsf{F}}',
  sG: '{\\mathsf{G}}',
  sH: '{\\mathsf{H}}',
  sI: '{\\mathsf{I}}',
  sJ: '{\\mathsf{J}}',
  sK: '{\\mathsf{K}}',
  sL: '{\\mathsf{L}}',
  sM: '{\\mathsf{M}}',
  sN: '{\\mathsf{N}}',
  sO: '{\\mathsf{O}}',
  sP: '{\\mathsf{P}}',
  sQ: '{\\mathsf{Q}}',
  sR: '{\\mathsf{R}}',
  sS: '{\\mathsf{S}}',
  sT: '{\\mathsf{T}}',
  sU: '{\\mathsf{U}}',
  sV: '{\\mathsf{V}}',
  sW: '{\\mathsf{W}}',
  sX: '{\\mathsf{X}}',
  sY: '{\\mathsf{Y}}',
  sZ: '{\\mathsf{Z}}',

  // ===== MATHBF LETTERS =====
  bA: '{\\mathbf{A}}',
  bB: '{\\mathbf{B}}',
  bC: '{\\mathbf{C}}',
  bD: '{\\mathbf{D}}',
  bE: '{\\mathbf{E}}',
  bF: '{\\mathbf{F}}',
  bG: '{\\mathbf{G}}',
  bH: '{\\mathbf{H}}',
  bI: '{\\mathbf{I}}',
  bJ: '{\\mathbf{J}}',
  bK: '{\\mathbf{K}}',
  bL: '{\\mathbf{L}}',
  bM: '{\\mathbf{M}}',
  bN: '{\\mathbf{N}}',
  bO: '{\\mathbf{O}}',
  bP: '{\\mathbf{P}}',
  bQ: '{\\mathbf{Q}}',
  bR: '{\\mathbf{R}}',
  bS: '{\\mathbf{S}}',
  bT: '{\\mathbf{T}}',
  bU: '{\\mathbf{U}}',
  bV: '{\\mathbf{V}}',
  bW: '{\\mathbf{W}}',
  bX: '{\\mathbf{X}}',
  bY: '{\\mathbf{Y}}',
  bZ: '{\\mathbf{Z}}',
  bdelta: '{\\mathbf{\\Delta}}',
  blambda: '{\\mathbf{\\Lambda}}',

  // ===== CATEGORY THEORY COMMANDS =====
  cat: ['{\\mathsf{#1}}', 1],
  tcat: ['{\\mathbf{#1}}', 1],
  ms: ['{\\mathscr{#1}}', 1],
  bDelta: '{\\mathbf{\\Delta}}',
  bTheta: '{\\mathbf{\\Theta}}',

  // Category names and operations
  hSpectra: '{\\mathsf{hSpectra}}',
  Schemes: '{\\mathsf{Schemes}}',
  Rmod: ['{\\mathsf{Mod}_{#1}}', 1],
  modR: ['{{}_{ #1}\\mathsf{Mod}}', 1],
  hTop: '{\\mathsf{hTop}}',
  Top: '{\\mathsf{Top}}',
  hocat: ['{\\mathscr{ho}(\\mathsf{#1})}', 1],
  Fun: '{\\mathsf{Fun}}',
  Alg: '{\\mathsf{Alg}}',
  spaces: '{\\mathcal{S}}',
  Spaces: '{\\mathcal{S}}',
  spectra: '{\\mathcal{S}\\mathsf{p}}',
  Spectra: '{\\mathcal{S}\\mathsf{p}}',
  Sp: '{\\mathcal{S}\\mathsf{p}}',
  ho: '{\\mathsf{h}}',
  chom: '{\\mathsf{hom}}',
  hom: '{\\mathsf{hom}}',
  ob: '{\\mathsf{ob}}',
  lim: '{\\mathsf{lim}}',
  Mot: '{\\mathsf{Mot}}',
  Pre: '{\\mathcal{P}}',
  fgt: '{\\mathsf{fgt}}',
  simp: '{\\mathsf{s}}',
  bisimp: '{\\mathsf{ss}}',
  sSet: '{\\mathsf{sSet}}',
  Joyal: '{\\mathsf{Joyal}}',
  St: '{\\mathsf{St}}',
  Cat: '{\\mathsf{Cat}}',
  op: '{\\mathsf{op}}',
  fin: '{\\mathsf{fin}}',
  Yo: '{\\mathsf{Yo}}',
  ex: '{\\mathsf{ex}}',
  twoex: '{2\\text{-}\\mathsf{ex}}',
  Vex: '{\\mathcal{V}\\text{-}\\mathsf{ex}}',
  cotensor: '{\\pitchfork}',
  tensor: '{\\odot}',
  loc: '{\\mathsf{loc}}',
  Ab: '{\\mathsf{Ab}}',
  CMon: '{\\mathsf{CMon}}',
  THH: '{\\mathsf{THH}}',
  enr: '{\\text{-}\\mathsf{enr}}',
  Ord: '{\\mathsf{Ord}}',
  Sh: '{\\mathsf{Sh}}',
  Open: '{\\mathsf{Open}}',
  FinSet: '{\\mathsf{FinSet}}',
  inj: '{\\mathsf{inj}}',
  Card: '{\\mathsf{Card}}',
  heart: '{\\heartsuit}',
  LFib: '{\\mathsf{LFib}}',
  RFib: '{\\mathsf{RFib}}',
  Disk: '{\\mathcal{D}\\mathsf{isk}}',
  Mfld: '{\\mathcal{M}\\mathsf{fld}}',
  shom: '{\\mathscr{H}\\mathrm{om}}',
  K: '{\\mathsf{K}}',
  Kto: '{\\mathsf{K}^{(2,1)}}',
  Ktwo: '{\\mathsf{K}^{(2)}}',
  oneLoc: '{\\mathsf{1Loc}}',
  Adj: '{\\mathsf{Adj}}',
  zeroLoc: '{\\mathsf{0Loc}}',
  Perf: '{\\mathsf{Perf}}',
  Ind: '{\\mathsf{Ind}}',
  cofib: '{\\mathsf{cofib}}',
  fib: '{\\mathsf{fib}}',
  Fib: '{\\mathsf{Fib}}',
  opFib: '{\\mathsf{opFib}}',
  pseudo: '{\\mathsf{pseudo}}',
  CAlg: '{\\mathsf{CAlg}}',
  ulFun: '{\\underline{\\mathsf{Fun}}}',
  dzbl: '{\\mathsf{dzbl}}',
  LKan: '{\\mathsf{LKan}}',
  TC: '{\\mathsf{TC}}',
  tr: '{\\mathsf{tr}}',
  trmon: '{\\mathsf{tr}}',
  QCtwo: '{\\mathsf{QC}^{(2)}}',
  THHtwo: '{\\mathsf{THH}^{(2)}}',
  TCtwo: '{\\mathsf{TC}^{(2)}}',
  Perftwo: '{\\mathsf{Perf}^{(2)}}',
  Cyclo: '{\\mathsf{Cyc}}',
  Cyclic: '{\\mathsf{C}}',
  trtwo: '{\\mathsf{tr}^{(2)}}',
  Vect: '{\\mathsf{Vect}}',
  Set: '{\\mathsf{Set}}',
  Grp: '{\\mathsf{Grp}}',
  Cyl: '{\\mathsf{Cyl}}',
  Nat: '{\\mathsf{Nat}}',
  Gpd: '{\\mathsf{Gpd}}',
  cf: '{\\mathsf{cf}}',
  QCat: '{\\mathsf{QCat}}',
  cart: '{\\mathsf{cart}}',
  Cart: '{\\mathsf{Cart}}',
  colim: '{\\mathsf{colim}}',
  SH: '{\\mathsf{SH}}',
  Env: '{\\mathsf{Env}}',
  Un: '{\\mathsf{Un}}',
  Str: '{\\mathsf{Str}}',
  End: '{\\mathsf{end}}',
  Ar: '{\\mathsf{Ar}}',
  fCat: '{\\mathsf{fCat}}',
  Mod: '{\\mathsf{Mod}}',
  univ: '{\\mathcal{L}}',
  const: '{\\mathsf{const}}',
  uno: '{\\mathbbm{1}}',
  Add: '{\\mathsf{Add}}',
  ev: '{\\mathsf{ev}}',
  idem: '{\\mathsf{idem}}',
  id: '{\\mathsf{id}}',
  nerve: '{\\mathsf{N}}',
  da: '{\\downarrow}',
  coCart: '{\\mathsf{coCart}}',
  htpy: '{\\mathsf{h}}',
  equ: '{\\mathsf{equ}}',
  cocart: '{\\mathsf{cocart}}',
  Gr: '{\\mathsf{Gr}}',
  Fin: '{\\mathsf{Fin}}',
  th: '{^{\\text{th}}}',
  QC: '{\\mathsf{QC}}',
  BiMod: '{\\mathsf{BiMod}}',
  PrLSt: '{\\mathsf{Pr}^{L,\\mathsf{st}}}',
  PrL: '{\\mathsf{Pr}^L}',
  PrR: '{\\mathsf{Pr}^R}',
  PrRSt: '{\\mathsf{Pr}^{R,\\mathsf{st}}}',
  what: ['{\\widehat{#1}}', 1],
  PrSt: '{\\mathsf{Pr}^{\\mathsf{st}}}',
  Poset: '{\\mathsf{Poset}}',
  oneop: '{1\\text{-}\\mathsf{op}}',
  twoop: '{2\\text{-}\\mathsf{op}}',
  kop: '{k\\text{-}\\mathsf{op}}',
  onetwoop: '{1\\&2\\text{-}\\mathsf{op}}',
  LMod: '{\\mathsf{LMod}}',
  RMod: '{\\mathsf{RMod}}',
  MMot: '{\\mathbb{M}\\mathsf{ot}}',
  pt: '{\\mathsf{pt}}',
  Free: '{\\mathsf{Free}}',
  weak: '{\\flat}',
  sadd: '{\\mathsf{semiadd}}',
  add: '{\\mathsf{add}}',
  ShvCat: '{\\mathsf{ShvCat}}',
  Aut: '{\\mathsf{aut}}',
  aut: '{\\mathsf{aut}}',
  sat: '{\\mathsf{sat}}',
  Var: '{\\mathsf{Var}}',
  inn: '{\\mathsf{inn}}',
  Spin: '{\\mathsf{Spin}}',
  Mat: '{\\mathsf{Mat}}',
  TwArr: '{\\mathsf{TwArr}}',
  CGWH: '{\\mathsf{CGWH}}',
  boundary: '{\\partial}',
  Ch: '{\\mathsf{Ch}}',
  loccoCart: '{\\mathsf{loc.coCart}}',
  loccocart: '{\\mathsf{loc.cocart}}',
  locCart: '{\\mathsf{loc.Cart}}',
  loccart: '{\\mathsf{loc.cart}}',
  act: '{\\mathsf{act}}',
  inrt: '{\\mathsf{inrt}}',
  Opd: '{\\mathsf{Opd}}',
  rlax: '{\\mathsf{rlax}}',
  ReLU: '{\\mathsf{ReLU}}',
  Fit: '{\\mathsf{Fit}}',
  fpset: ['{\\langle #1 \\rangle_*}', 1],
  Tuple: '{\\mathsf{Tuple}}',
  Comm: '{\\mathsf{Comm}}',
  NestTuple: '{\\mathsf{NestTuple}}',
  Nest: '{\\mathsf{Nest}}',
  Flat: '{\\mathsf{Flat}}',
  reduce: '{\\mathsf{reduce}}',
  Softmax: '{\\mathsf{Softmax}}',
  size: '{\\mathsf{size}}',
  mode: '{\\mathsf{mode}}',
  Refine: '{\\mathsf{Ref}}',
  Fact: '{\\mathsf{Fact}}',
  Leaves: '{\\mathsf{Leaves}}',

  // ===== ARROWS AND SYMBOLS =====
  ra: '{\\rightarrow}',
  la: '{\\leftarrow}',
  longhookra: '{\\lhook\\joinrel\\longrightarrow}',
  adjarr: '{\\rightleftarrows}',
  xra: ['{\\xrightarrow{#1}}', 1],
  xla: ['{\\xleftarrow{#1}}', 1],
  longla: '{\\longleftarrow}',
  longra: '{\\longrightarrow}',
  xlongra: ['{\\stackrel{#1}{\\longrightarrow}}', 1],
  xlongla: ['{\\stackrel{#1}{\\longleftarrow}}', 1],
  adj: '{\\dashv}',

  // ===== MISCELLANEOUS SHORTCUTS =====
  ul: ['{\\underline{#1}}', 1],
  bit: ['{\\textbf{\\textit{#1}}}', 1],
  ulhom: '{\\underline{\\mathsf{hom}}}',
  es: '{\\varnothing}',
  msf: ['{\\mathsf{#1}}', 1],
}

// Helper function to convert macros to MathJax-ready format
// Doubles backslashes for proper escaping in the HTML script tag
export function getMathJaxMacrosString() {
  const entries = Object.entries(mathjaxMacros).map(([key, value]) => {
    if (Array.isArray(value)) {
      const [def, args] = value
      const escapedDef = def.replace(/\\/g, '\\\\')
      return `${key}: ['${escapedDef}', ${args}]`
    } else {
      const escapedValue = value.replace(/\\/g, '\\\\')
      return `${key}: '${escapedValue}'`
    }
  })
  return `{\n            ${entries.join(',\n            ')}\n          }`
}
